import {test} from 'node:test';
import assert from 'node:assert/strict';
import {normalizeInsertRequest,insertEdges,insertLanding,insertTargetSnapshot,insertDisclosure,adapterReadiness,intentPrompt,insertIntent,resolutionTier,GENERATED_AUDIO_POLICY} from '../public/insert-contract.mjs';
const edit={format:'shutter-media-edit-v1',fps:'24000/1001',width:1920,height:1080,clips:[
 {id:'a',assetId:'asset_a',sourceStart:'1/2',frames:48,fit:'cover',sampling:{origin:'0/1',offsetFrames:12}},
 {id:'b',assetId:'asset_b',sourceStart:'0/1',frames:72,fit:'contain'}
]};
const request={requestKey:'insert_01',baseRevision:7,clipId:'a',kind:'bridge',prompt:'Dissolve naturally into the next shot.',duration:5,resolution:'768P',quality:'balanced',maxUsd:.75,acknowledgeUnmanagedColor:true};
test('normalization is strict and stable',()=>assert.deepEqual(normalizeInsertRequest(request),{schema:'shutter-generative-insert-v1',...request}));
test('balanced / faithful is the default expansion mode',()=>assert.equal(normalizeInsertRequest(Object.fromEntries(Object.entries(request).filter(([k])=>k!=='quality'))).quality,'balanced'));
test('unknown settings and implicit color consent fail',()=>{assert.throws(()=>normalizeInsertRequest({...request,secret:true}),/insert_request_invalid/);assert.throws(()=>normalizeInsertRequest({...request,acknowledgeUnmanagedColor:false}),/reference_color_review_required/);});
test('alternate uses first and last frame of one shot',()=>assert.deepEqual(insertEdges(edit,'a','alternate'),[{clipId:'a',edge:'start',role:'opening-frame',authority:'boundary'},{clipId:'a',edge:'end',role:'ending-frame',authority:'boundary'}]));
test('continue starts from the accepted ending frame',()=>assert.deepEqual(insertEdges(edit,'a','continue'),[{clipId:'a',edge:'end',role:'opening-frame',authority:'boundary'}]));
test('new angle splits appearance authority from prior motion',()=>{assert.deepEqual(insertEdges(edit,'a','new-angle'),[{clipId:'a',edge:'end',role:'appearance-state',authority:'appearance-state'}]);const intent=insertIntent('new-angle');assert.equal(intent.providerMode,'reference-to-video');assert.equal(intent.referenceAuthority[1].authority,'motion-time');});
test('bridge is explicitly bounded by both adjacent shots',()=>assert.deepEqual(insertEdges(edit,'a','bridge'),[{clipId:'a',edge:'end',role:'opening-frame',authority:'boundary'},{clipId:'b',edge:'start',role:'ending-frame',authority:'boundary'}]));
test('arrive conditions on destination start and lands before it',()=>{assert.deepEqual(insertEdges(edit,'b','arrive'),[{clipId:'b',edge:'start',role:'ending-frame',authority:'destination'}]);assert.deepEqual(insertLanding(edit,'b','arrive'),{kind:'insert-before',leftClipId:'a',rightClipId:'b'});});
test('bridge at the end is rejected rather than inventing a destination',()=>assert.throws(()=>insertEdges(edit,'b','bridge'),/insert_bridge_needs_next_shot/));
test('landing policy keeps replace and insertion semantics distinct',()=>{assert.deepEqual(insertLanding(edit,'a','alternate'),{kind:'take-stack',clipId:'a'});assert.deepEqual(insertLanding(edit,'a','continue'),{kind:'insert-after',leftClipId:'a',rightClipId:'b'});assert.deepEqual(insertLanding(edit,'a','new-angle'),{kind:'insert-after',leftClipId:'a',rightClipId:'b'});assert.deepEqual(insertLanding(edit,'a','bridge'),{kind:'insert-between',leftClipId:'a',rightClipId:'b'});});
test('target snapshot carries only fields that affect the reviewed reference composition',()=>assert.deepEqual(insertTargetSnapshot(edit,'a','bridge'),{fps:'24000/1001',width:1920,height:1080,kind:'bridge',clipId:'a',clips:[{...edit.clips[0]},{...edit.clips[1],sampling:null}]}));
test('disclosure distinguishes still and motion material leaving the device',()=>assert.deepEqual(insertDisclosure([{kind:'image'},{kind:'video'}]),{leavesDeviceOnSubmission:['prompt','1 derived PNG reference image','1 derived motion reference video'],staysLocal:['camera originals','master soundtrack','sound lanes','finishing text','unselected library media'],providerContacted:false,submissionState:'not-submitted',generatedAudioPolicy:GENERATED_AUDIO_POLICY}));
test('resolution profiles are draft review and finish',()=>{assert.equal(resolutionTier('480P'),'draft');assert.equal(resolutionTier('768P'),'review');assert.equal(resolutionTier('1080P'),'finish');});
test('live-validated I2V adapter carries 1080P while Ref2V 1080 stays blocked',()=>{assert.equal(adapterReadiness({...request,resolution:'1080P'}).adapterReady,true);const angle={...request,kind:'new-angle',resolution:'1080P'};assert.equal(adapterReadiness(angle).adapterReady,false);assert.match(adapterReadiness(angle).reason,/1080_unqualified/);assert.equal(adapterReadiness({...angle,resolution:'480P'}).adapterReady,true);});
test('new-angle direction explicitly requests a new no-cut shot and no score',()=>{const p=intentPrompt('new-angle','Track the rider.');assert.match(p,/Begin immediately from that new angle/i);assert.match(p,/no internal cuts/i);assert.match(p,/No non-diegetic music/i);});
test('bridge direction admits creative transition instead of promising literal physics',()=>assert.match(intentPrompt('bridge','Cross worlds.'),/do not claim literal continuous physics/i));
test('duration and hard spend limit are bounded',()=>{assert.throws(()=>normalizeInsertRequest({...request,duration:4}),/insert_duration/);assert.throws(()=>normalizeInsertRequest({...request,maxUsd:0}),/insert_spend_limit/);assert.throws(()=>normalizeInsertRequest({...request,maxUsd:101}),/insert_spend_limit/);});
