import {test,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {planGenerativeInsert,readGenerativeInsert,listGenerativeInserts,discardGenerativeInsert,quoteGenerativeInsert,submitGenerativeInsert,reconcileGenerativeInsert} from '../src/generative-inserts.mjs';
import {applyGeneratedInsert} from '../src/generative-insert-apply.mjs';
class Studio{
 constructor(root){this.root=root;this.records=new Map();this.jobs=new Map();this.timelineRevision=7;this.production={id:'prod_demo',title:'Midnight',revision:3,shots:[],cast:[]};this.timeline={format:'shutter-media-edit-v1',fps:'24',width:1920,height:1080,clips:[{id:'a',assetId:'asset_a',sourceStart:'0/1',frames:48,fit:'cover'},{id:'b',assetId:'asset_b',sourceStart:'0/1',frames:72,fit:'contain'}],soundtrack:{assetId:'master',tailPolicy:'pad-silence'},markers:[{id:'chorus',frame:48,label:'Chorus',kind:'chorus'}],textLayer:{schema:'shutter-text-v1',captionDelivery:'sidecar',cues:[]}};this.plan={hash:'plan7',format:this.timeline.format,fps:'24/1',width:1920,height:1080,clips:[{...this.timeline.clips[0],at:0,sourceKind:'video',sampling:{origin:'0/1',offsetFrames:0}},{...this.timeline.clips[1],at:48,sourceKind:'video',sampling:{origin:'0/1',offsetFrames:0}}]};
  this.write('asset',{id:'asset_a',sha256:'a'.repeat(64),filename:'a'.repeat(64)+'.mp4',bytes:1,kind:'video',mime:'video/mp4',name:'A'});this.write('asset',{id:'asset_b',sha256:'b'.repeat(64),filename:'b'.repeat(64)+'.mp4',bytes:1,kind:'video',mime:'video/mp4',name:'B'});
  this.write('media-profile',{id:'media_asset_a',assetId:'asset_a',assetSha256:'a'.repeat(64),kind:'video',width:1920,height:1080,videoStream:0,duration:10});this.write('media-profile',{id:'media_asset_b',assetId:'asset_b',assetSha256:'b'.repeat(64),kind:'video',width:1920,height:1080,videoStream:0,duration:10});
  this.db={prepare:()=>({get:id=>{const r=this.records.get(id);return r?{kind:r.kind}:undefined;}})};
 }
 getProduction(id){if(id!=='prod_demo')throw Error('not_found');return structuredClone(this.production);}
 getTimeline(id){if(id!=='prod_demo')throw Error('not_found');return {id:'timeline_demo',projectId:id,revision:this.timelineRevision,timeline:structuredClone(this.timeline),plan:structuredClone(this.plan)};}
 write(kind,value){if(kind==='job'){this.jobs.set(value.id,structuredClone(value));return structuredClone(value);}this.records.set(value.id,{kind,value:structuredClone(value)});return structuredClone(value);}
 read(id,kind){const r=this.records.get(id);if(!r||r.kind!==kind)throw Error('not_found');return structuredClone(r.value);}
 list(kind){return [...this.records.values()].filter(r=>r.kind===kind).map(r=>structuredClone(r.value));}
 transaction(fn){return fn();}
 assetPath(id){return path.join(this.root,id+'.bin');}
 verifyAsset(id){return this.read(id,'asset');}
 getJob(id){const j=this.jobs.get(id);if(!j)throw Error('not_found');return structuredClone(j);}
 listJobs(){return [...this.jobs.values()].map(j=>structuredClone(j));}
 updateJob(id,patch){const j={...this.getJob(id),...structuredClone(patch)};this.jobs.set(id,j);return structuredClone(j);}
 saveTimeline(id,baseRevision,next){if(id!=='prod_demo'||this.timelineRevision!==baseRevision)throw Error('revision_conflict');this.timeline=structuredClone(next);this.timelineRevision++;let at=0;this.plan={...this.plan,hash:'plan'+this.timelineRevision,clips:this.timeline.clips.map(c=>{const p={...c,at,sourceKind:'video',sampling:c.sampling??{origin:c.sourceStart??'0/1',offsetFrames:0}};at+=c.frames;return p;})};return this.getTimeline(id);}
}
let roots=[];afterEach(async()=>{for(const r of roots.splice(0))await fs.rm(r,{recursive:true,force:true});globalThis.__insertImported=0;globalThis.__insertInspect=null;});
const make=async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'insert-test-'));roots.push(root);return new Studio(root);};
const req=(kind='bridge')=>({requestKey:'request_1',baseRevision:7,clipId:'a',kind,prompt:'Let the movement become a dark glass dream.',duration:5,resolution:'768P',quality:'balanced',maxUsd:1,acknowledgeUnmanagedColor:true});
test('planning derives only reviewed boundary frames and never creates a provider job',async()=>{const s=await make(),p=await planGenerativeInsert(s,'prod_demo',req());assert.equal(p.state,'planned');assert.equal(p.references.length,2);assert.equal(p.disclosure.submissionState,'not-submitted');assert.equal(p.landing.kind,'insert-between');assert.equal(s.listJobs().length,0);assert.equal(s.timeline.clips[0].assetId,'asset_a');assert.equal(s.timeline.clips[1].assetId,'asset_b');assert.equal(listGenerativeInserts(s,'prod_demo').length,1);assert.equal(readGenerativeInsert(s,'prod_demo',p.id).current,true);});
test('same request key is idempotent and conflicting intent is rejected',async()=>{const s=await make(),first=await planGenerativeInsert(s,'prod_demo',req());const again=await planGenerativeInsert(s,'prod_demo',req());assert.equal(again.id,first.id);assert.equal(s.list('generative-insert').length,1);await assert.rejects(planGenerativeInsert(s,'prod_demo',{...req(),prompt:'Different intent'}),/insert_request_conflict/);});
test('saved cut changing during frame derivation prevents a plan from being rebound',async()=>{const s=await make();let once=false;globalThis.__insertInspect=async()=>{if(!once){once=true;s.timelineRevision=8;}};await assert.rejects(planGenerativeInsert(s,'prod_demo',req('continue')),/revision_conflict/);assert.equal(s.list('generative-insert').length,0);});
test('quote stores live-provider evidence without authorizing a paid submission',async()=>{const s=await make(),plan=await planGenerativeInsert(s,'prod_demo',req('alternate'));const fake={prepare:async id=>s.updateJob(id,{quote:{pool:'imageReference',estimatedUsd:.2,reservedUsd:.2,baseRate:.025,outputRate:.04,preparedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()}})};const quoted=await quoteGenerativeInsert(s,'prod_demo',plan.id,{baseRevision:plan.revision},{fal:fake});assert.equal(quoted.state,'quoted');assert.equal(quoted.spending.authorized,false);assert.equal(quoted.disclosure.submissionState,'not-submitted');assert.equal(s.getJob(quoted.jobId).snapshot.timelineRevision,7);});
test('a quoted plan can be discarded without provider submission and cancels its prepared job',async()=>{const s=await make(),plan=await planGenerativeInsert(s,'prod_demo',req('alternate'));const quote={pool:'imageReference',estimatedUsd:.2,reservedUsd:.2,baseRate:.025,outputRate:.04,preparedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()};const quoted=await quoteGenerativeInsert(s,'prod_demo',plan.id,{baseRevision:plan.revision},{fal:{prepare:async id=>s.updateJob(id,{quote})}});const discarded=discardGenerativeInsert(s,'prod_demo',quoted.id,{baseRevision:quoted.revision});assert.equal(discarded.state,'discarded');assert.equal(s.getJob(quoted.jobId).state,'cancelled');assert.equal(s.getJob(quoted.jobId).providerId,null);});
test('submission requires exact quote authorization and ambiguous receipt is never retried',async()=>{const s=await make(),plan=await planGenerativeInsert(s,'prod_demo',req('alternate'));const quote={pool:'imageReference',estimatedUsd:.2,reservedUsd:.2,baseRate:.025,outputRate:.04,preparedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()};const quoteProvider={prepare:async id=>s.updateJob(id,{quote})};let record=await quoteGenerativeInsert(s,'prod_demo',plan.id,{baseRevision:plan.revision},{fal:quoteProvider});await assert.rejects(submitGenerativeInsert(s,'prod_demo',record.id,{baseRevision:record.revision,authorize:true,acceptDisclosure:false,acceptedReservedUsd:.2},{fal:{}}),/insert_authorization_required/);const unknownProvider={submit:async id=>{s.updateJob(id,{state:'unknown',error:'network_after_send'});throw Error('network_after_send');}};record=await submitGenerativeInsert(s,'prod_demo',record.id,{baseRevision:record.revision,authorize:true,acceptDisclosure:true,acceptedReservedUsd:.2},{fal:unknownProvider});assert.equal(record.state,'unknown');assert.equal(record.disclosure.submissionState,'uncertain');});
test('ready alternate becomes an unaccepted Take Stack candidate while the cut stays unchanged',async()=>{const s=await make(),plan=await planGenerativeInsert(s,'prod_demo',req('alternate'));const quote={pool:'imageReference',estimatedUsd:.2,reservedUsd:.2,baseRate:.025,outputRate:.04,preparedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()};let record=await quoteGenerativeInsert(s,'prod_demo',plan.id,{baseRevision:plan.revision},{fal:{prepare:async id=>s.updateJob(id,{quote})}});record=await submitGenerativeInsert(s,'prod_demo',record.id,{baseRevision:record.revision,authorize:true,acceptDisclosure:true,acceptedReservedUsd:.2},{fal:{submit:async id=>s.updateJob(id,{state:'rendering',providerId:'provider_1',receipt:{}})}});
 const output='asset_'+('c'.repeat(64));s.write('asset',{id:output,sha256:'c'.repeat(64),filename:'c'.repeat(64)+'.mp4',bytes:1,kind:'video',mime:'video/mp4',name:'Generated'});s.write('media-profile',{id:'media_'+output,assetId:output,assetSha256:'c'.repeat(64),kind:'video',width:1366,height:768,videoStream:0,duration:5});s.updateJob(record.jobId,{state:'ready',output,media:{duration:5},charge:{actualUsd:.19}});
 const ready=await reconcileGenerativeInsert(s,'prod_demo',record.id,{baseRevision:record.revision},{fal:{reconcile:async id=>s.getJob(id)}});assert.equal(ready.state,'ready-candidate');const stack=s.read('stack_a','take-stack');assert.ok(stack.candidates.some(c=>c.insertId===record.id&&c.evidence==='generated-candidate'));assert.equal(s.timeline.clips[0].assetId,'asset_a');});
test('continue output remains a deliberate insert candidate and never rewrites the timeline automatically',async()=>{const s=await make(),plan=await planGenerativeInsert(s,'prod_demo',req('continue'));const quote={pool:'imageReference',estimatedUsd:.2,reservedUsd:.2,baseRate:.025,outputRate:.04,preparedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()};let record=await quoteGenerativeInsert(s,'prod_demo',plan.id,{baseRevision:plan.revision},{fal:{prepare:async id=>s.updateJob(id,{quote})}});record=await submitGenerativeInsert(s,'prod_demo',record.id,{baseRevision:record.revision,authorize:true,acceptDisclosure:true,acceptedReservedUsd:.2},{fal:{submit:async id=>s.updateJob(id,{state:'rendering',providerId:'provider_1',receipt:{}})}});const output='asset_'+('d'.repeat(64));s.write('asset',{id:output,sha256:'d'.repeat(64),filename:'d'.repeat(64)+'.mp4',bytes:1,kind:'video',mime:'video/mp4',name:'Continuation'});s.write('media-profile',{id:'media_'+output,assetId:output,assetSha256:'d'.repeat(64),kind:'video',width:1366,height:768,videoStream:0,duration:5});s.updateJob(record.jobId,{state:'ready',output,media:{duration:5},charge:{actualUsd:.19}});const ready=await reconcileGenerativeInsert(s,'prod_demo',record.id,{baseRevision:record.revision},{fal:{reconcile:async id=>s.getJob(id)}});assert.equal(ready.state,'ready-insert');assert.equal(ready.landingResult.attached,false);assert.equal(s.timeline.clips.length,2);});

test('ready continuation is inserted only after an explicit revision-guarded apply and leaves song clock metadata untouched',async()=>{const s=await make(),plan=await planGenerativeInsert(s,'prod_demo',req('continue'));const quote={pool:'imageReference',estimatedUsd:.2,reservedUsd:.2,baseRate:.025,outputRate:.04,preparedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()};let record=await quoteGenerativeInsert(s,'prod_demo',plan.id,{baseRevision:plan.revision},{fal:{prepare:async id=>s.updateJob(id,{quote})}});record=await submitGenerativeInsert(s,'prod_demo',record.id,{baseRevision:record.revision,authorize:true,acceptDisclosure:true,acceptedReservedUsd:.2},{fal:{submit:async id=>s.updateJob(id,{state:'rendering',providerId:'provider_2',receipt:{}})}});const output='asset_'+('e'.repeat(64));s.write('asset',{id:output,sha256:'e'.repeat(64),filename:'e'.repeat(64)+'.mp4',bytes:1,kind:'video',mime:'video/mp4',name:'Continuation'});s.write('media-profile',{id:'media_'+output,assetId:output,assetSha256:'e'.repeat(64),kind:'video',width:1366,height:768,videoStream:0,duration:5});s.updateJob(record.jobId,{state:'ready',output,media:{duration:5},charge:{actualUsd:.19}});record=await reconcileGenerativeInsert(s,'prod_demo',record.id,{baseRevision:record.revision},{fal:{reconcile:async id=>s.getJob(id)}});const soundtrack=structuredClone(s.timeline.soundtrack),markers=structuredClone(s.timeline.markers),text=structuredClone(s.timeline.textLayer);const applied=await applyGeneratedInsert(s,'prod_demo',record.id,{baseRevision:record.revision,timelineRevision:7});assert.equal(applied.insert.state,'applied-insert');assert.equal(applied.timeline.revision,8);assert.equal(s.timeline.clips.length,3);assert.equal(s.timeline.clips[1].assetId,output);assert.equal(s.timeline.clips[1].frames,120);assert.deepEqual(s.timeline.soundtrack,soundtrack);assert.deepEqual(s.timeline.markers,markers);assert.deepEqual(s.timeline.textLayer,text);});
