import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {PeakAccumulator,analyzeWaveform,readWaveform} from '../src/media-waveform.mjs';import {Studio} from '../src/store.mjs';import {runMedia,importMediaFile,fileDigest} from '../src/media-io.mjs';
let root,studio,source;
before(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'shutter-waveform-'));studio=new Studio(path.join(root,'data'));const file=path.join(root,'antiphase.wav');await runMedia('ffmpeg',['-v','error','-f','lavfi','-i','aevalsrc=0.8*sin(2*PI*440*t)|-0.8*sin(2*PI*440*t):s=48000:d=0.5','-c:a','pcm_s24le',file]);source=await importMediaFile(studio,file);});
after(async()=>{studio?.close();if(root)await fs.rm(root,{recursive:true,force:true});});
const floats=frames=>{const b=Buffer.alloc(frames.length*8);frames.forEach((f,i)=>{b.writeFloatLE(f[0],i*8);b.writeFloatLE(f[1],i*8+4);});return b;};
test('stream chunk boundaries do not change min/max envelopes',()=>{const frames=Array.from({length:1200},(_,i)=>[Math.sin(i),Math.cos(i)]),data=floats(frames),a=new PeakAccumulator({samplesPerBin:32,maxBins:8}),b=new PeakAccumulator({samplesPerBin:32,maxBins:8});a.push(data);for(let i=0;i<data.length;i+=7)b.push(data.subarray(i,i+7));assert.deepEqual(a.finish(),b.finish());});
test('bounded compaction retains independent per-channel extrema and exact sample count',()=>{
  const frames=Array.from({length:501},(_,i)=>[i===255?0.75:-0.25,i===499?-0.875:0.125]),a=new PeakAccumulator({samplesPerBin:4,maxBins:8});a.push(floats(frames));const result=a.finish();assert.equal(result.sampleFrames,501);assert.ok(result.peaks[0].length<=16);
  for(let c=0;c<2;c++)for(let i=0;i<result.peaks[c].length/2;i++){const values=frames.slice(i*result.samplesPerBin,(i+1)*result.samplesPerBin).map(f=>f[c]);assert.equal(result.peaks[c][2*i],Math.min(...values));assert.equal(result.peaks[c][2*i+1],Math.max(...values));}
});
test('truncated samples, NaN and duration overflow do not become valid envelopes',()=>{const a=new PeakAccumulator();a.push(Buffer.alloc(3));assert.throws(()=>a.finish(),/truncated/);const b=new PeakAccumulator();assert.throws(()=>b.push(floats([[NaN,0]])),/nonfinite/);const c=new PeakAccumulator({maxSamples:1});assert.throws(()=>c.push(floats([[0,0],[1,1]])),/duration_limit/);});
test('silence stays zero and is not normalized to a false signal',()=>{const a=new PeakAccumulator();a.push(floats(Array.from({length:500},()=>[0,0])));const w=a.finish();assert.equal(w.samplePeak,0);assert.ok(w.peaks.flat().every(x=>x===0));});
test('real anti-phase PCM is visible on both channels rather than cancelling in a mono sum',async()=>{const original=await fileDigest(studio.assetPath(source.id)),w=await analyzeWaveform(studio,source.id);assert.equal(w.channels,2);assert.equal(w.sampleFrames,24000);assert.ok(Math.max(...w.peaks[0])>0.79);assert.ok(Math.max(...w.peaks[1])>0.79);assert.ok(Math.min(...w.peaks[1])<-.79);assert.equal(await fileDigest(studio.assetPath(source.id)),original);});
test('successful cache is reused without running the decoder again',async()=>{const first=await analyzeWaveform(studio,source.id),old=process.env.SHUTTER_FFMPEG;process.env.SHUTTER_FFMPEG='/nonexistent-decoder';try{const second=await analyzeWaveform(studio,source.id);assert.deepEqual(second,first);}finally{if(old===undefined)delete process.env.SHUTTER_FFMPEG;else process.env.SHUTTER_FFMPEG=old;}});
test('cache reads verify original bytes and fail closed after source corruption',async()=>{const file=studio.assetPath(source.id),original=await fs.readFile(file);try{const changed=Buffer.from(original);changed[changed.length-1]^=1;await fs.writeFile(file,changed);await assert.rejects(readWaveform(studio,source.id),/asset_integrity/);}finally{await fs.writeFile(file,original);}});
test('pre-cancelled analysis creates no cache entry',async()=>{const file=path.join(root,'cancel.wav');await runMedia('ffmpeg',['-v','error','-f','lavfi','-i','sine=frequency=300:duration=0.1','-c:a','pcm_s16le',file]);const a=await importMediaFile(studio,file),controller=new AbortController();controller.abort();await assert.rejects(analyzeWaveform(studio,a.id,{signal:controller.signal}),/cancelled/);assert.equal(studio.list('media-waveform').filter(w=>w.assetId===a.id).length,0);});
