import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {Studio,fingerprint} from '../src/store.mjs';
import {runMedia,importMediaFile,fileDigest} from '../src/media-io.mjs';
import {createMediaProduction} from '../src/media-api.mjs';
import {saveMoment,searchMoments,deleteMoment,getTakeStack,collectTake,acceptTake,exportProductionMemory,ensureMemory} from '../src/production-memory.mjs';
import {scoutAsset,readScoutImage} from '../src/media-scout.mjs';
import {renderMediaEdit} from '../src/media-edit.mjs';
import {applyEdit} from '../public/music-edit.mjs';
import {pcm24} from './helpers/sound-fixtures.mjs';
let root,studio,original,alternate,song,p;
const note=(id='moment_night',overrides={})=>({id,assetId:alternate.id,startUs:0,endUs:2000000,label:'Night close-up',notes:'Looking left before the chorus. Café.',tags:['night','performance','camera'],favorite:true,...overrides});
const project=()=>createMediaProduction(studio,{title:'Production memory fixture',fps:'24',width:320,height:180}).production;
function cut(prod){const t=studio.getTimeline(prod.id).timeline;t.clips=[{id:'shot',assetId:original.id,sourceStart:'0',frames:24,fit:'contain'}];t.soundtrack={assetId:song.id,tailPolicy:'pad-silence'};t.markers=[{id:'chorus',frame:12,kind:'chorus',label:'Chorus'}];t.textLayer={schema:'shutter-text-v1',captionDelivery:'sidecar',cues:[{id:'title',kind:'title',startFrame:0,endFrame:10,text:'SHUTTER'}]};return studio.saveTimeline(prod.id,1,t);}
before(async()=>{
 root=await fs.mkdtemp(path.join(os.tmpdir(),'shutter-memory-'));studio=new Studio(path.join(root,'studio'));
 const a=path.join(root,'original.mp4'),b=path.join(root,'alternate.mp4');
 await runMedia('ffmpeg',['-v','error','-f','lavfi','-i','color=black:s=320x180:r=24:d=1','-f','lavfi','-i','color=white:s=320x180:r=24:d=1','-f','lavfi','-i','color=red:s=320x180:r=24:d=1','-filter_complex','[0:v][1:v][2:v]concat=n=3:v=1:a=0','-threads','1','-c:v','libx264',a]);
 await runMedia('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=s=320x180:r=24:d=3','-threads','1','-c:v','libx264',b]);
 original=await importMediaFile(studio,a,{name:'C0037-camera.mp4'});alternate=await importMediaFile(studio,b,{name:'Alternate-light.mp4'});
 const wav=path.join(root,'song.wav');await fs.writeFile(wav,pcm24(144000,(i,c)=>(i*(c+2))%24000-12000));song=await importMediaFile(studio,wav,{name:'Unchanged master.wav'});p=project();cut(p);
});
after(async()=>{studio.close();await fs.rm(root,{recursive:true,force:true});});
test('notes index real source intervals and tags while leaving edit and original files unchanged',async()=>{const before=studio.getTimeline(p.id),hash=await fileDigest(studio.assetPath(alternate.id));const m=await saveMoment(studio,p.id,note());assert.equal(m.evidence,'artist-authored');assert.equal(m.sourceSha256,alternate.sha256);assert.equal(m.revision,1);assert.deepEqual(studio.getTimeline(p.id),before);assert.equal(await fileDigest(studio.assetPath(alternate.id)),hash);const found=searchMoments(studio,p.id,{query:'night clos'});assert.equal(found.results[0].id,m.id);});
test('FTS searches filename, note and diacritics but does not invent visual concepts',()=>{assert.equal(searchMoments(studio,p.id,{query:'cafe'}).total,1);assert.equal(searchMoments(studio,p.id,{query:'Alternate'}).total,1);assert.equal(searchMoments(studio,p.id,{query:'spaceship'}).total,0);assert.equal(searchMoments(studio,p.id,{query:'"*()'}).total,0);});
test('note edits atomically replace old index entries and reject stale revisions',async()=>{const m=await saveMoment(studio,p.id,note('moment_night',{label:'Quiet wide shot',tags:['wide'],notes:'Silhouette by the water.'}),{baseRevision:1});assert.equal(m.revision,2);assert.equal(searchMoments(studio,p.id,{query:'night'}).total,0);assert.equal(searchMoments(studio,p.id,{query:'silhouette'}).total,1);await assert.rejects(saveMoment(studio,p.id,note(),{baseRevision:1}),/conflict/);assert.equal(searchMoments(studio,p.id,{query:'silhouette'}).total,1);});
test('projects are isolated and a global note id cannot be rebound',async()=>{const other=project();assert.equal(searchMoments(studio,other.id).total,0);await assert.rejects(saveMoment(studio,other.id,note(),{baseRevision:2}),/identity_conflict/);assert.equal(searchMoments(studio,other.id).total,0);});
test('a forged note id cannot overwrite a timeline or another record kind',async()=>{const id='timeline_'+p.id,before=studio.read(id);await assert.rejects(saveMoment(studio,p.id,note(id)),/identity_conflict/);assert.deepEqual(studio.read(id),before);});
test('favorite and media filters have bounded pagination',async()=>{await saveMoment(studio,p.id,note('moment_extra',{favorite:false,label:'Extra angle'}));const first=searchMoments(studio,p.id,{limit:1});assert.equal(first.total,2);assert.equal(first.nextOffset,1);assert.equal(searchMoments(studio,p.id,{favorite:true}).total,1);assert.equal(searchMoments(studio,p.id,{kind:'audio'}).total,0);assert.throws(()=>searchMoments(studio,p.id,{limit:999}),/options/);});
test('out-of-source ranges are rejected without partial records',async()=>{await assert.rejects(saveMoment(studio,p.id,note('moment_long',{endUs:3000001})),/source_range/);assert.equal(searchMoments(studio,p.id).total,2);});
test('collecting a moment keeps the original selection without modifying the timeline',async()=>{const before=studio.getTimeline(p.id);const stack=await collectTake(studio,p.id,'shot',{baseRevision:before.revision,stackRevision:0,momentId:'moment_extra',momentRevision:1});assert.equal(stack.candidates.length,2);assert.equal(stack.candidates[0].current,true);assert.equal(stack.candidates[1].label,'Extra angle');assert.deepEqual(studio.getTimeline(p.id),before);});
test('candidate collection is revision guarded and deduplicates the same note snapshot',async()=>{const current=studio.getTimeline(p.id);await assert.rejects(collectTake(studio,p.id,'shot',{baseRevision:current.revision,stackRevision:0,momentId:'moment_extra',momentRevision:1}),/stack_revision_conflict/);const s=await collectTake(studio,p.id,'shot',{baseRevision:current.revision,stackRevision:1,momentId:'moment_extra',momentRevision:1});assert.equal(s.candidates.length,2);await assert.rejects(collectTake(studio,p.id,'shot',{baseRevision:current.revision,stackRevision:s.revision,momentId:'moment_extra',momentRevision:0}),/memory_revision_conflict/);});
test('take acceptance changes only shot source, and undo restores the exact previous timeline',async()=>{const before=studio.getTimeline(p.id),stack=getTakeStack(studio,p.id,'shot');const result=await acceptTake(studio,p.id,'shot',{baseRevision:before.revision,stackRevision:stack.revision,candidateId:stack.candidates[1].id});assert.equal(result.timeline.clips[0].assetId,alternate.id);assert.equal(result.timeline.clips[0].frames,24);for(const k of ['soundtrack','markers','textLayer'])assert.deepEqual(result.timeline[k],before.timeline[k]);assert.deepEqual(studio.undoTimeline(p.id,result.revision).timeline,before.timeline);});
test('too-short collected ranges stay available but cannot silently stretch into the shot',async()=>{const m=await saveMoment(studio,p.id,note('moment_short',{startUs:0,endUs:1000})),r=studio.getTimeline(p.id),s=await collectTake(studio,p.id,'shot',{baseRevision:r.revision,stackRevision:getTakeStack(studio,p.id,'shot').revision,momentId:m.id,momentRevision:1});const candidate=s.candidates.find(c=>c.momentId===m.id);assert.equal(candidate.fits,false);await assert.rejects(acceptTake(studio,p.id,'shot',{baseRevision:r.revision,stackRevision:s.revision,candidateId:candidate.id}),/short/);assert.equal(studio.getTimeline(p.id).revision,r.revision);});
test('a timeline edit during async source verification rejects the stale take proposal',async()=>{const r=studio.getTimeline(p.id),s=getTakeStack(studio,p.id,'shot'),pending=acceptTake(studio,p.id,'shot',{baseRevision:r.revision,stackRevision:s.revision,candidateId:s.candidates[1].id});const next=structuredClone(r.timeline);next.clips[0].fit='cover';const saved=studio.saveTimeline(p.id,r.revision,next);await assert.rejects(pending,/revision_conflict/);assert.deepEqual(studio.getTimeline(p.id).timeline,saved.timeline);});
test('deleting a note removes search results but preserves collected evidence snapshots',()=>{const s=getTakeStack(studio,p.id,'shot');deleteMoment(studio,p.id,'moment_extra',1);assert.equal(searchMoments(studio,p.id,{query:'Extra angle'}).total,0);assert.deepEqual(getTakeStack(studio,p.id,'shot').candidates,s.candidates);});
test('reopen rebuilds identical search results and preserves stack provenance',()=>{const before=exportProductionMemory(studio,p.id);studio.close();studio=new Studio(path.join(root,'studio'));assert.equal(searchMoments(studio,p.id,{query:'silhouette'}).total,1);assert.deepEqual(exportProductionMemory(studio,p.id),before);});
test('FTS rebuild repairs a deleted derived index without changing authored evidence',()=>{const m=studio.read('moment_night','memory-moment');studio.db.exec('DELETE FROM memory_search_v1');studio.close();studio=new Studio(path.join(root,'studio'));assert.equal(searchMoments(studio,p.id,{query:'silhouette'}).total,1);assert.deepEqual(studio.read(m.id,'memory-moment'),m);});
test('local scout finds the two known synthetic changes and records nominal source ranges',async()=>{const before=studio.getTimeline(p.id),scout=await scoutAsset(studio,original.id,{startUs:0,endUs:3000000});assert.deepEqual(scout.sceneTimesUs,[1000000,2000000]);assert.equal(scout.images.length,3);for(const img of scout.images){const bytes=await readScoutImage(studio,scout.id,img.index);assert.equal(bytes[0],255);assert.equal(bytes[1],216);}assert.deepEqual(studio.getTimeline(p.id),before);assert.equal(await fileDigest(studio.assetPath(original.id)),original.sha256);});
test('cached scout is reused, not silently relabeled as a new analysis',async()=>{const scout=await scoutAsset(studio,original.id,{startUs:0,endUs:3000000});assert.equal(scout.cached,true);assert.equal(studio.list('memory-scout').length,1);});
test('scout respects nonzero source origins and cannot process an oversized requested range',async()=>{const scout=await scoutAsset(studio,original.id,{startUs:1000000,endUs:3000000});assert.deepEqual(scout.sceneTimesUs,[2000000]);assert.equal(scout.ranges[0].startUs,1000000);await assert.rejects(scoutAsset(studio,original.id,{startUs:0,endUs:121000000}),/range_limit/);});
test('cancelled scouting cannot publish a ready analysis',async()=>{const abort=new AbortController();abort.abort();const before=studio.list('memory-scout').length;await assert.rejects(scoutAsset(studio,alternate.id,{startUs:0,endUs:3000000},{signal:abort.signal}),/cancelled/);assert.equal(studio.list('memory-scout').length,before);});
test('source corruption blocks acceptance instead of trusting a saved label',async()=>{const r=studio.getTimeline(p.id),s=getTakeStack(studio,p.id,'shot'),file=studio.assetPath(alternate.id),bytes=await fs.readFile(file);await fs.writeFile(file,Buffer.alloc(bytes.length));try{await assert.rejects(acceptTake(studio,p.id,'shot',{baseRevision:r.revision,stackRevision:s.revision,candidateId:s.candidates[1].id}),/integrity/);assert.equal(studio.getTimeline(p.id).revision,r.revision);}finally{await fs.writeFile(file,bytes);}});
test('actual export after take selection retains aligned master; original re-selection restores decoded picture',async()=>{
 const prod=project(),r=cut(prod),first=await renderMediaEdit(studio,prod.id,{baseRevision:r.revision,acknowledgeUnmanagedColor:true});
 const m=await saveMoment(studio,prod.id,note('moment_export')),s=await collectTake(studio,prod.id,'shot',{baseRevision:r.revision,stackRevision:0,momentId:m.id,momentRevision:1});
 const accepted=await acceptTake(studio,prod.id,'shot',{baseRevision:r.revision,stackRevision:s.revision,candidateId:s.candidates[1].id}),second=await renderMediaEdit(studio,prod.id,{baseRevision:accepted.revision,acknowledgeUnmanagedColor:true});
 const wave=c=>path.join(studio.root,'media-renders',c.bridgeFolder,'master-48k.wav');assert.equal(await fileDigest(wave(first)),await fileDigest(wave(second)));
 const restored=await acceptTake(studio,prod.id,'shot',{baseRevision:accepted.revision,stackRevision:s.revision,candidateId:s.candidates[0].id}),third=await renderMediaEdit(studio,prod.id,{baseRevision:restored.revision,acknowledgeUnmanagedColor:true});
 const frames=async c=>(await runMedia('ffmpeg',['-v','error','-i',studio.assetPath(c.output),'-map','0:v:0','-f','framemd5','-'])).split('\n').filter(l=>!l.startsWith('#')&&l.trim());
 assert.deepEqual(await frames(first),await frames(third));assert.notDeepEqual(await frames(first),await frames(second));assert.equal(await fileDigest(studio.assetPath(song.id)),song.sha256);
});
test('original split phase survives collecting and accepting another take',async()=>{
 const prod=project(),r=cut(prod),profiles=new Map([[original.id,studio.read('media_'+original.id)]]);const split=applyEdit(r.timeline,{type:'split',clipId:'shot',frame:8,newId:'right'},profiles),saved=studio.saveTimeline(prod.id,r.revision,split);
 const m=await saveMoment(studio,prod.id,note('moment_phase')),s=await collectTake(studio,prod.id,'right',{baseRevision:saved.revision,stackRevision:0,momentId:m.id,momentRevision:1});
 const change=await acceptTake(studio,prod.id,'right',{baseRevision:saved.revision,stackRevision:s.revision,candidateId:s.candidates[1].id}),restored=await acceptTake(studio,prod.id,'right',{baseRevision:change.revision,stackRevision:s.revision,candidateId:s.candidates[0].id});
 assert.deepEqual(restored.timeline.clips[1].sampling,saved.timeline.clips[1].sampling);assert.equal(restored.timeline.clips[1].sourceStart,saved.timeline.clips[1].sourceStart);
});

test('explicit scout rerun repairs a missing derived thumbnail without touching the source',async()=>{const prior=await scoutAsset(studio,original.id,{startUs:0,endUs:3000000});await fs.rm(path.join(studio.root,'memory-cache',prior.folder,prior.images[0].name));const next=await scoutAsset(studio,original.id,{startUs:0,endUs:3000000});assert.equal(next.rebuilt,true);assert.notEqual(next.folder,prior.folder);assert.equal(await fileDigest(studio.assetPath(original.id)),original.sha256);assert.ok((await readScoutImage(studio,next.id,0)).length);});
test('one-frame scout range has a real thumbnail rather than a fabricated final frame',async()=>{const scout=await scoutAsset(studio,original.id,{startUs:0,endUs:41666});assert.equal(scout.images.length,1);assert.equal(scout.images[0].timeUs,0);});

test('scout cache identity cannot overwrite an unrelated authored record',async()=>{const options={startUs:0,endUs:500000,threshold:10},id='scout_'+fingerprint({schema:'shutter-scout-v1',assetId:alternate.id,sourceSha256:alternate.sha256,options});const saved=await saveMoment(studio,p.id,note(id));await assert.rejects(scoutAsset(studio,alternate.id,options),/identity_conflict/);assert.deepEqual(studio.read(id),saved);});
