import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {runMedia} from '../src/media-io.mjs';
let child,base,root,record,project;
const request=(url,input,method='POST',extra={})=>fetch(base+url,{method,headers:{'content-type':'application/json',...extra},body:JSON.stringify(input)});
const put=command=>request(`/api/media/productions/${project}/commands`,{baseRevision:record.revision,command});
before(async()=>{
 root=await fs.mkdtemp(path.join(os.tmpdir(),'text-http-'));
 child=spawn(process.execPath,['--loader','./test/helpers/media-server-loader.mjs','./test/helpers/media-http-server.mjs'],{cwd:fileURLToPath(new URL('../',import.meta.url)),stdio:['ignore','pipe','pipe']});
 const info=await new Promise((resolve,reject)=>{let output='',error='';const timer=setTimeout(()=>reject(Error(error||'server_timeout')),10000);child.stderr.on('data',b=>error+=b);child.stdout.on('data',b=>{output+=b;try{const parsed=JSON.parse(output.trim());clearTimeout(timer);resolve(parsed);}catch{}});child.on('exit',code=>{clearTimeout(timer);reject(Error('server_exit '+code+' '+error));});});base=`http://127.0.0.1:${info.port}`;
 const file=path.join(root,'picture.mp4');await runMedia('ffmpeg',['-v','error','-f','lavfi','-i','color=black:s=320x180:r=24','-frames:v','24','-c:v','libx264','-threads','1',file]);
 const asset=await(await fetch(base+'/api/media/assets?name=Synthetic.mp4',{method:'POST',body:await fs.readFile(file)})).json();
 const made=await(await request('/api/media/productions',{title:'HTTP text fixture',fps:'24',width:320,height:180})).json();project=made.production.id;
 const timeline={...made.timeline.timeline,clips:[{id:'shot',assetId:asset.id,sourceStart:'0',frames:24,fit:'contain'}]};record=await(await request(`/api/media/productions/${project}/timeline`,{baseRevision:1,timeline},'PUT')).json();
});
after(async()=>{if(child&&child.exitCode===null){child.kill('SIGTERM');await once(child,'exit');}await fs.rm(root,{recursive:true,force:true});});
test('actual server serves finishing modules and mounts the editor',async()=>{for(const [file,type] of [['text-edit.mjs','javascript'],['text-room.js','javascript'],['text-room.css','css']]){const r=await fetch(base+'/'+file);assert.equal(r.status,200);assert.ok(r.headers.get('content-type').includes(type));}assert.ok((await(await fetch(base+'/media-studio')).text()).includes('id="text-room"'));});
test('text commands save through existing revisioned timeline records',async()=>{const response=await put({type:'text-put',cue:{id:'title',kind:'title',startFrame:0,endFrame:8,text:'SHUTTER'}});assert.equal(response.status,200);record=await response.json();assert.equal(record.plan.version,7);assert.equal(record.timeline.textLayer.cues[0].text,'SHUTTER');});
test('foreign-origin compositor request is denied before rendering',async()=>{const r=await request(`/api/media/productions/${project}/text-preview`,{baseRevision:record.revision,frame:0,acknowledgeUnmanagedColor:true},'POST',{origin:'https://other.invalid'});assert.equal(r.status,403);});
test('stale text command returns conflict and keeps the current title',async()=>{const r=await request(`/api/media/productions/${project}/commands`,{baseRevision:1,command:{type:'text-delete',cueId:'title'}});assert.equal(r.status,409);assert.equal((await r.json()).error,'revision_conflict');});
test('invalid renderer markup is rejected rather than written',async()=>{const r=await put({type:'text-put',cue:{id:'bad',kind:'title',startFrame:0,endFrame:8,text:'{\\pos(1,1)}'}});assert.equal(r.status,400);const current=await(await fetch(base+`/api/media/productions/${project}/timeline`)).json();assert.equal(current.revision,record.revision);assert.equal(current.timeline.textLayer.cues.length,1);});
test('plain caption import is one revision and leaves title and picture intact',async()=>{const r=await put({type:'text-import',mode:'replace-captions',sourceFormat:'srt',idPrefix:'lyrics',content:'1\n00:00:00,500 --> 00:00:01,000\nA line from your song.'});assert.equal(r.status,200);record=await r.json();assert.equal(record.timeline.textLayer.cues.length,2);assert.equal(record.timeline.clips.length,1);});
test('caption delivery is an explicit saved command',async()=>{const r=await put({type:'text-delivery',delivery:'burn-and-sidecar'});assert.equal(r.status,200);record=await r.json();assert.equal(record.timeline.textLayer.captionDelivery,'burn-and-sidecar');});
test('actual compositor endpoint returns a saved frame asset with exact revision identity',async()=>{const r=await request(`/api/media/productions/${project}/text-preview`,{baseRevision:record.revision,frame:0,acknowledgeUnmanagedColor:true});assert.equal(r.status,201);const frame=await r.json();assert.equal(frame.revision,record.revision);assert.equal(frame.planHash,record.plan.hash);const image=await fetch(base+'/media/'+frame.imageAssetId);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');});
test('undo and redo restore captions through the original history route',async()=>{const previous=record;let r=await request(`/api/media/productions/${project}/timeline/undo`,{baseRevision:record.revision});assert.equal(r.status,200);record=await r.json();assert.equal(record.timeline.textLayer.captionDelivery,'sidecar');r=await request(`/api/media/productions/${project}/timeline/redo`,{baseRevision:record.revision});record=await r.json();assert.deepEqual(record.timeline,previous.timeline);});
test('rendered handoff exposes the actual subtitle bytes and blocks unlisted paths',async()=>{const r=await request(`/api/media/productions/${project}/render`,{baseRevision:record.revision,acknowledgeUnmanagedColor:true});assert.equal(r.status,200);const cut=await r.json();for(const name of ['captions.srt','captions.vtt','text-layer.json']){const f=await fetch(base+`/api/media/cuts/${cut.id}/files/${name}`);assert.equal(f.status,200);assert.ok((await f.text()).length>20);}assert.equal((await fetch(base+`/api/media/cuts/${cut.id}/files/nonexistent.txt`)).status,404);});
