/** Governed Generative Insert lifecycle. Planning is local-only; provider contact happens only during explicit quote/submission/reconcile steps. */
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fingerprint} from './store.mjs';
import {getMediaProfile,verifyMediaAsset,importMediaFile,ensureMediaProfile,decoderArgs} from './media-io.mjs';
import {inspectProcess} from './media-inspect.mjs';
import {mediaPictureFilters,MEDIA_EDIT_FORMAT} from './media-edit.mjs';
import {normalizeInsertRequest,insertEdges,insertLanding,insertTargetSnapshot,insertDisclosure,adapterReadiness,intentPrompt,insertIntent,resolutionTier,GENERATED_AUDIO_POLICY} from '../public/insert-contract.mjs';
import {MEMORY_LIMITS,sourceSelection,sameSelection} from '../public/memory-contract.mjs';
import {getTakeStack} from './production-memory.mjs';
import {h3Snapshot} from './h3-spec.mjs';
import {FalRenderer} from './fal-renderer.mjs';

const kind='generative-insert';
const providers=new WeakMap();
const providerFor=studio=>{let provider=providers.get(studio);if(!provider){provider=new FalRenderer(studio);providers.set(studio,provider);}return provider;};
const safeId=value=>typeof value==='string'&&/^insert_[a-f0-9]{64}$/.test(value);
const insertId=(projectId,requestKey)=>'insert_'+fingerprint(['generative-insert-v1',projectId,requestKey]);
const rateValue=fps=>{const m=String(fps).match(/^(\d{1,9})(?:\/(\d{1,9}))?$/);if(!m)throw Error('insert_timeline_rate');const n=Number(m[1]),d=Number(m[2]||1),v=n/d;if(!Number.isFinite(v)||n<=0||d<=0)throw Error('insert_timeline_rate');return v;};
function rowKind(studio,id){return studio.db.prepare('SELECT kind FROM records WHERE id=?').get(id)?.kind||null;}
function optional(studio,id){const k=rowKind(studio,id);if(!k)return null;if(k!==kind)throw Error('insert_identity_conflict');return studio.read(id,kind);}
function requireProject(studio,projectId){if(typeof projectId!=='string'||!/^prod_[A-Za-z0-9-]+$/.test(projectId))throw Error('insert_project');studio.getProduction(projectId);}
function timeline(studio,projectId){const record=studio.getTimeline(projectId);if(record.timeline?.format!==MEDIA_EDIT_FORMAT)throw Error('media_edit_required');return record;}
function targetHash(edit,clipId,insertKind){return fingerprint(insertTargetSnapshot(edit,clipId,insertKind));}
function publicRecord(studio,record){const current=timeline(studio,record.projectId);let sameTarget=false,targetStatus=null;try{sameTarget=targetHash(current.timeline,record.request.clipId,record.request.kind)===record.targetFingerprint;}catch(e){targetStatus=e.message;}return {...record,currentTimelineRevision:current.revision,revisionCurrent:current.revision===record.timelineRevision,targetCurrent:sameTarget,targetStatus,current:current.revision===record.timelineRevision&&sameTarget};}
export function readGenerativeInsert(studio,projectId,id){requireProject(studio,projectId);if(!safeId(id))throw Error('not_found');const value=studio.read(id,kind);if(value.projectId!==projectId)throw Error('not_found');return publicRecord(studio,value);}
export function listGenerativeInserts(studio,projectId,{clipId=null,limit=50}={}){requireProject(studio,projectId);if(clipId!==null&&(typeof clipId!=='string'||!/^[A-Za-z0-9_-]{1,100}$/.test(clipId)))throw Error('insert_clip_id');if(!Number.isSafeInteger(limit)||limit<1||limit>100)throw Error('insert_list_limit');return studio.list(kind).filter(x=>x.projectId===projectId&&(!clipId||x.request.clipId===clipId)).slice(-limit).reverse().map(x=>publicRecord(studio,x));}
function planClip(record,clipId){const clip=record.plan.clips.find(c=>c.id===clipId);if(!clip)throw Error('insert_target_missing');return clip;}
async function renderEdge(studio,record,edge,folder,index,{signal}={}){
 const target=planClip(record,edge.clipId);if(target.frames<1)throw Error('insert_empty_target');
 const outputFrame=target.at+(edge.edge==='start'?0:target.frames-1),clip=(record.plan.pictureClips||record.plan.clips).find(c=>c.at<=outputFrame&&outputFrame<c.at+c.frames);if(!clip)throw Error('insert_target_missing');
 const profile=getMediaProfile(studio,clip.assetId),source=await verifyMediaAsset(studio,clip.assetId);if(!['video','image'].includes(profile.kind))throw Error('visual_media_required');
 const offset=outputFrame-clip.at,sampling=clip.sampling||{origin:clip.sourceStart??'0/1',offsetFrames:0};const one={...clip,frames:1,sampling:{origin:sampling.origin,offsetFrames:sampling.offsetFrames+offset}};
 const output=path.join(folder,`reference-${index+1}.png`),filters=mediaPictureFilters(record.plan,one,profile)+',format=rgb24';
 await inspectProcess('ffmpeg',['-v','error','-nostdin',...decoderArgs,...(profile.kind==='image'?['-loop','1','-framerate',record.plan.fps]:[]),'-i',studio.assetPath(clip.assetId),'-map',`0:${profile.videoStream}`,'-vf',filters,'-frames:v','1','-fps_mode','vfr','-an','-sn','-dn','-c:v','png','-threads','1','-filter_threads','1','-map_metadata','-1',output],{timeoutMs:600000,maxBytes:1024*1024,signal});
 const stat=await fs.lstat(output);if(!stat.isFile()||stat.size<32)throw Error('insert_reference_render_failed');const after=await verifyMediaAsset(studio,clip.assetId);if(after.sha256!==source.sha256)throw Error('asset_integrity');
 return {output,kind:'image',role:edge.role,authority:edge.authority||'boundary',edge:edge.edge,sourceClipId:clip.id,sourceAssetId:clip.assetId,sourceSha256:source.sha256,outputFrame,colorPolicy:'composition-unmanaged-sdr-reference',fit:clip.fit};
}
async function renderMotionTail(studio,record,clipId,folder,{signal}={}){
 const clip=planClip(record,clipId),profile=getMediaProfile(studio,clip.assetId),source=await verifyMediaAsset(studio,clip.assetId);if(profile.kind!=='video')throw Error('insert_new_angle_requires_video');
 const fps=rateValue(record.plan.fps),tailFrames=Math.min(clip.frames,Math.max(1,Math.round(fps*5))),offset=clip.frames-tailFrames,sampling=clip.sampling||{origin:clip.sourceStart??'0/1',offsetFrames:0},tail={...clip,frames:tailFrames,sampling:{origin:sampling.origin,offsetFrames:sampling.offsetFrames+offset}};
 if(record.plan.coverage?.some(c=>c.at<clip.at+clip.frames&&c.at+c.frames>clip.at+offset))throw Error('insert_motion_tail_contains_coverage');
 const output=path.join(folder,'motion-tail.mp4'),filters=mediaPictureFilters(record.plan,tail,profile);
 await inspectProcess('ffmpeg',['-v','error','-nostdin',...decoderArgs,'-i',studio.assetPath(clip.assetId),'-map',`0:${profile.videoStream}`,'-vf',filters,'-frames:v',String(tailFrames),'-r',record.plan.fps,'-fps_mode','cfr','-an','-sn','-dn','-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p','-threads','2','-filter_threads','1','-map_metadata','-1','-movflags','+faststart',output],{timeoutMs:600000,maxBytes:4*1024*1024,signal});
 const stat=await fs.lstat(output);if(!stat.isFile()||stat.size<128)throw Error('insert_motion_reference_failed');const after=await verifyMediaAsset(studio,clip.assetId);if(after.sha256!==source.sha256)throw Error('asset_integrity');
 return {output,kind:'video',role:'motion-time',authority:'motion-time',edge:'tail',sourceClipId:clip.id,sourceAssetId:clip.assetId,sourceSha256:source.sha256,outputFrameStart:clip.at+offset,outputFrameEnd:clip.at+clip.frames,frames:tailFrames,durationSeconds:tailFrames/fps,colorPolicy:'composition-unmanaged-sdr-reference',fit:clip.fit,audioIncluded:false};
}
async function importReference(studio,projectId,request,record,item){const extension=item.kind==='video'?'.mp4':'.png',imported=await importMediaFile(studio,item.output,{name:`${studio.getProduction(projectId).title} · ${request.kind} · ${item.role}${extension}`,origin:`Shutter Generative Insert local ${item.kind} reference; ${item.sourceClipId} ${item.edge}; no provider contacted`}),derivationId='derivation_'+crypto.randomUUID();studio.write('media-derivation',{id:derivationId,outputAssetId:imported.id,recipe:{operation:item.kind==='video'?'generative-insert-motion-reference':'generative-insert-reference',projectId,timelineRevision:record.revision,targetClipId:request.clipId,kind:request.kind,role:item.role,authority:item.authority,edge:item.edge,sourceClipId:item.sourceClipId,sourceAssetId:item.sourceAssetId,sourceSha256:item.sourceSha256,outputFrame:item.outputFrame??null,outputFrameStart:item.outputFrameStart??null,outputFrameEnd:item.outputFrameEnd??null,frames:item.frames??null,audioIncluded:item.audioIncluded??null,fit:item.fit,colorPolicy:item.colorPolicy},createdAt:new Date().toISOString()});return {...item,output:undefined,assetId:imported.id,sha256:imported.sha256,derivationId};}
export async function planGenerativeInsert(studio,projectId,input,{signal}={}){
 requireProject(studio,projectId);const request=normalizeInsertRequest(input),record=timeline(studio,projectId);if(request.baseRevision!==record.revision)throw Error('revision_conflict');
 const edges=insertEdges(record.timeline,request.clipId,request.kind),targetFingerprint=targetHash(record.timeline,request.clipId,request.kind),landing=insertLanding(record.timeline,request.clipId,request.kind),id=insertId(projectId,request.requestKey),specHash=fingerprint({projectId,timelineRevision:record.revision,request,targetFingerprint,landing}),prior=optional(studio,id);if(prior){if(prior.specHash!==specHash)throw Error('insert_request_conflict');return publicRecord(studio,prior);}
 const root=path.join(studio.root,'media-tmp');await fs.mkdir(root,{recursive:true});const folder=await fs.mkdtemp(path.join(root,'insert-plan-'));
 try{
  const rendered=[];for(let i=0;i<edges.length;i++){if(signal?.aborted)throw Error('insert_plan_cancelled');rendered.push(await renderEdge(studio,record,edges[i],folder,i,{signal}));}if(request.kind==='new-angle'){if(signal?.aborted)throw Error('insert_plan_cancelled');rendered.push(await renderMotionTail(studio,record,request.clipId,folder,{signal}));}if(signal?.aborted)throw Error('insert_plan_cancelled');
  const fresh=timeline(studio,projectId);if(fresh.revision!==record.revision||targetHash(fresh.timeline,request.clipId,request.kind)!==targetFingerprint)throw Error('revision_conflict');const references=[];for(const item of rendered)references.push(await importReference(studio,projectId,request,record,item));
  const readiness=adapterReadiness(request),opening=references.find(r=>r.role==='opening-frame'),ending=references.find(r=>r.role==='ending-frame'),packet=readiness.workflow.endsWith('/reference-to-video')?{workflow:readiness.workflow,mode:'reference-to-video',prompt:intentPrompt(request.kind,request.prompt),duration:request.duration,resolution:request.resolution,promptExpansionMode:request.quality,referenceAssets:references.map(r=>({assetId:r.assetId,kind:r.kind,role:r.role,authority:r.authority}))}:{workflow:readiness.workflow,mode:'image-to-video',prompt:intentPrompt(request.kind,request.prompt),duration:request.duration,resolution:request.resolution,promptExpansionMode:request.quality,...(opening?{imageAssetId:opening.assetId}:{}),...(ending?{endImageAssetId:ending.assetId}:{})};
  const finalRecord=timeline(studio,projectId);if(finalRecord.revision!==record.revision||targetHash(finalRecord.timeline,request.clipId,request.kind)!==targetFingerprint)throw Error('revision_conflict');
  const value={id,schema:'shutter-generative-insert-plan-v2',projectId,revision:1,state:'planned',requestKey:request.requestKey,specHash,timelineRevision:record.revision,planHash:record.plan.hash,targetFingerprint,request,landing,references:references.map(({output,...r})=>r),referenceAuthority:insertIntent(request.kind).referenceAuthority,providerIntent:{...readiness,packet},disclosure:insertDisclosure(references),spending:{hardLimitUsd:request.maxUsd,quote:null,authorized:false,spentUsd:0},renderProfile:{tier:resolutionTier(request.resolution),resolution:request.resolution,promptExpansion:request.quality,generatedAudioPolicy:GENERATED_AUDIO_POLICY},createdAt:new Date().toISOString(),limitations:['Local plan only: no provider was contacted and no generation was submitted.','Derived references exclude the mastered soundtrack and finishing text. New Angle motion references are visual-only tails, not the whole camera source.','Reference frames/video condition generation; they do not independently prove identity, physics, continuity or a seamless transition.','Bridge is a creative transition intent: when boundaries differ, H3 may invent an occlusion, dissolve or transformation.','Live H3 provider submission, receipt reconciliation and billing were validated on 2026-09-12; visual preservation still requires artist review.']};
  const collision=rowKind(studio,id);if(collision&&collision!==kind)throw Error('insert_identity_conflict');if(collision){const existing=studio.read(id,kind);if(existing.specHash!==specHash)throw Error('insert_request_conflict');return publicRecord(studio,existing);}studio.write(kind,value);return publicRecord(studio,value);
 }finally{await fs.rm(folder,{recursive:true,force:true});}
}
function stripComputed(record){return Object.fromEntries(Object.entries(record).filter(([k])=>!['currentTimelineRevision','revisionCurrent','targetCurrent','targetStatus','current'].includes(k)));}
export function discardGenerativeInsert(studio,projectId,id,{baseRevision}={}){requireProject(studio,projectId);const current=readGenerativeInsert(studio,projectId,id);if(!Number.isSafeInteger(baseRevision)||current.revision!==baseRevision)throw Error('revision_conflict');if(!['planned','quote-error','quoted','quoted-over-limit'].includes(current.state))throw Error('insert_discard_state');if(current.jobId){const job=studio.getJob(current.jobId);if(job.state==='prepared')studio.updateJob(job.id,{state:'cancelled',error:'insert_discarded_before_submission'});else if(!['cancelled','failed'].includes(job.state))throw Error('insert_discard_state');}const saved=studio.write(kind,{...stripComputed(current),state:'discarded',revision:current.revision+1,discardedAt:new Date().toISOString()});return publicRecord(studio,saved);}
const aspectFor=(w,h)=>{const r=w/h,candidates=[['16:9',16/9],['21:9',21/9],['4:3',4/3],['1:1',1],['3:4',3/4],['9:16',9/16]],best=candidates.sort((a,b)=>Math.abs(a[1]-r)-Math.abs(b[1]-r))[0];return Math.abs(best[1]-r)<.03?best[0]:'adaptive';};
function providerShot(studio,record){const opening=record.references.find(r=>r.role==='opening-frame'),ending=record.references.find(r=>r.role==='ending-frame'),intent=insertIntent(record.request.kind),mode=intent.providerMode,project=studio.getProduction(record.projectId),shot={id:record.request.clipId,title:`${project.title} · ${record.request.kind}`,frames:record.request.duration*24,fps:24,width:record.request.resolution==='480P'?854:record.request.resolution==='768P'?1366:1920,height:Number(record.request.resolution.slice(0,-1)),action:intentPrompt(record.request.kind,record.request.prompt),camera:'',sound:'Diegetic scene audio only. No non-diegetic music, score, captions or text. Generated audio must remain isolated from the Shutter master unless separately promoted.',cast:[],characterStates:[],generation:{model:'h3-max',mode,duration:record.request.duration,resolution:record.request.resolution,promptExpansionMode:record.request.quality,aspectRatio:aspectFor(timeline(studio,record.projectId).timeline.width,timeline(studio,record.projectId).timeline.height)}};if(mode==='image-to-video'){if(opening)shot.reference=opening.assetId;if(ending)shot.endReference=ending.assetId;shot.extraReferences=[];}else shot.extraReferences=record.references.map(r=>({assetId:r.assetId,role:r.authority==='appearance-state'?'authoritative current visible appearance/wardrobe/object state; appearance wins if references conflict':r.authority==='motion-time'?'prior visual motion and temporal continuity only; do not override the authoritative appearance still':'supporting reference: '+r.role}));const h3=h3Snapshot(studio,project,shot);return {project,shot,h3};}
function writeLifecycle(studio,record,patch){return publicRecord(studio,studio.write(kind,{...stripComputed(record),...patch,revision:record.revision+1,updatedAt:new Date().toISOString()}));}
export async function quoteGenerativeInsert(studio,projectId,id,{baseRevision}={}, {fal=providerFor(studio)}={}){let record=readGenerativeInsert(studio,projectId,id);if(!Number.isSafeInteger(baseRevision)||record.revision!==baseRevision)throw Error('revision_conflict');if(!['planned','quote-error','quoted','quoted-over-limit'].includes(record.state))throw Error('insert_quote_state');if(!record.current)throw Error('insert_target_stale');if(!record.providerIntent.adapterReady)throw Error(record.providerIntent.reason||'insert_adapter_not_qualified');let job=record.jobId?studio.getJob(record.jobId):null;if(!job){const {project,shot,h3}=providerShot(studio,record),snapshot={projectId,projectRevision:project.revision,timelineRevision:record.timelineRevision,insertId:record.id,targetFingerprint:record.targetFingerprint,spendLimitUsd:record.spending.hardLimitUsd,title:project.title,style:'Respect the declared reference authority and saved edit context. Do not add captions or non-diegetic music.',cast:[],place:h3.place||{},shot,references:h3.references,bindings:h3.bindings,workflow:h3.workflow};job=studio.write('job',{id:'job_'+crypto.randomUUID(),projectId,shotId:record.request.clipId,requestKey:'insert:'+record.requestKey,specHash:fingerprint(snapshot),snapshot,state:'prepared',providerId:null,output:null,review:null,createdAt:new Date().toISOString()});record=writeLifecycle(studio,record,{jobId:job.id,state:'quote-pending',quote:null,error:null});}try{job=await fal.prepare(job.id);const over=job.quote.reservedUsd>record.spending.hardLimitUsd+1e-9;return writeLifecycle(studio,record,{state:over?'quoted-over-limit':'quoted',quote:job.quote,error:over?'quote_exceeds_insert_spend_limit':null,disclosure:{...record.disclosure,providerContacted:true},spending:{...record.spending,quote:job.quote,authorized:false}});}catch(e){return writeLifecycle(studio,record,{state:'quote-error',error:e.message,disclosure:{...record.disclosure,providerContacted:e.message==='fal_key_missing'?record.disclosure.providerContacted:true}});}}
export async function submitGenerativeInsert(studio,projectId,id,input={}, {fal=providerFor(studio)}={}){let record=readGenerativeInsert(studio,projectId,id);if(!Number.isSafeInteger(input.baseRevision)||record.revision!==input.baseRevision)throw Error('revision_conflict');if(record.state!=='quoted'||!record.quote||!record.current)throw Error('insert_not_ready_to_submit');if(input.authorize!==true||input.acceptDisclosure!==true||typeof input.acceptedReservedUsd!=='number'||Math.abs(input.acceptedReservedUsd-record.quote.reservedUsd)>1e-9)throw Error('insert_authorization_required');if(Date.now()>Date.parse(record.quote.expiresAt))throw Error('quote_expired_prepare_again');if(record.quote.reservedUsd>record.spending.hardLimitUsd+1e-9)throw Error('insert_spend_limit_exceeded');record=writeLifecycle(studio,record,{state:'submitting',authorizedAt:new Date().toISOString(),error:null,spending:{...record.spending,authorized:true},disclosure:{...record.disclosure,submissionState:'attempting'}});try{const job=await fal.submit(record.jobId),state=job.state==='rendering'?'rendering':job.state;return writeLifecycle(studio,record,{state,error:job.error||null,providerId:job.providerId||null,disclosure:{...record.disclosure,submissionState:job.providerId?'submitted':'attempting'}});}catch(e){const job=studio.getJob(record.jobId);if(job.state==='unknown')return writeLifecycle(studio,record,{state:'unknown',error:job.error||e.message,providerId:job.providerId||null,disclosure:{...record.disclosure,submissionState:'uncertain'}});writeLifecycle(studio,record,{state:'quoted',error:e.message,spending:{...record.spending,authorized:false},disclosure:{...record.disclosure,submissionState:'not-submitted'}});throw e;}}
function cleanStack(stack){const {timelineRevision,shotFrames,fps,...base}=stack;return {...base,candidates:base.candidates.map(({fits,reason,current,...c})=>c)};}
function evidenceFor(record,job){const result=job.result||{};return {provider:'fal',workflow:job.snapshot.workflow,requestId:job.providerId||null,originalPrompt:record.request.prompt,expandedPrompt:result.expanded_prompt??null,seed:result.seed??null,timings:result.timings??null,promptExpansionMode:record.request.quality,estimatedUsd:job.quote?.estimatedUsd??null,reservedUsd:job.quote?.reservedUsd??null,actualUsd:job.charge?.actualUsd??null,billableUnits:job.charge?.billableUnits??null,referenceTokens:job.quote?.referenceTokens??0,referenceInputUsd:job.quote?.referenceInputUsd??0,visualContinuityStatus:'unreviewed',providerRetentionAnalysisIsNotIndependentEvidence:true};}
function audioHandling(profile){const streams=Array.isArray(profile.audio)?profile.audio.length:Number(profile.audioStreams||0);return {policy:GENERATED_AUDIO_POLICY,generatedAudioStreams:streams,masterChanged:false,soundStageChanged:false,note:'Generated video audio is never mixed into the mastered song or Sound Stage automatically. The artist may later extract/promote it as a separate sound candidate.'};}
async function attachAlternateCandidate(studio,record,job,providerEvidence,audio){const current=timeline(studio,record.projectId);if(current.revision!==record.timelineRevision||targetHash(current.timeline,record.request.clipId,record.request.kind)!==record.targetFingerprint)return {attached:false,reason:'target_stale'};const clip=current.timeline.clips.find(c=>c.id===record.request.clipId);if(!clip)return {attached:false,reason:'target_missing'};const output=await verifyMediaAsset(studio,job.output),profile=await ensureMediaProfile(studio,job.output);if(profile.kind!=='video')throw Error('generated_video_required');return studio.transaction(()=>{const now=timeline(studio,record.projectId);if(now.revision!==record.timelineRevision||targetHash(now.timeline,record.request.clipId,record.request.kind)!==record.targetFingerprint)return {attached:false,reason:'target_stale'};const currentClip=now.timeline.clips.find(c=>c.id===record.request.clipId),view=getTakeStack(studio,record.projectId,record.request.clipId),stack=cleanStack(view);if(stack.candidates.some(c=>c.insertId===record.id))return {attached:true,stackRevision:stack.revision,duplicate:true};if(!stack.candidates.some(c=>sameSelection(c,currentClip,now.timeline.fps))){const a=studio.read(currentClip.assetId,'asset'),p=getMediaProfile(studio,currentClip.assetId);stack.candidates.push({id:'take_'+crypto.randomUUID(),label:stack.candidates.length?'Prior selection':'Original selection',...sourceSelection(currentClip,now.timeline.fps),endUs:p.kind==='image'?MEMORY_LIMITS.rangeUs:Math.floor(p.duration*1e6),sourceSha256:a.sha256,evidence:'saved-shot',capturedRevision:now.revision});}stack.candidates.push({id:'take_'+crypto.randomUUID(),label:`Generated ${record.request.kind} · ${record.request.prompt.slice(0,80)}`,assetId:job.output,sourceStart:'0/1',endUs:Math.floor(profile.duration*1e6),sourceSha256:output.sha256,evidence:'generated-candidate',insertId:record.id,jobId:job.id,provider:'fal',workflow:job.snapshot.workflow,quote:record.quote,providerEvidence,audioHandling:audio,createdAt:new Date().toISOString()});if(stack.candidates.length>MEMORY_LIMITS.takes)throw Error('take_stack_limit');studio.write('take-stack',{...stack,revision:stack.revision+1,updatedAt:new Date().toISOString()});return {attached:true,stackRevision:stack.revision+1};});}
export async function reconcileGenerativeInsert(studio,projectId,id,{baseRevision}={}, {fal=providerFor(studio)}={}){let record=readGenerativeInsert(studio,projectId,id);if(!Number.isSafeInteger(baseRevision)||record.revision!==baseRevision)throw Error('revision_conflict');if(!record.jobId)throw Error('insert_job_missing');let job=studio.getJob(record.jobId);if(['rendering','verifying','unknown'].includes(job.state)&&job.providerId)job=await fal.reconcile(job.id);if(job.state==='unknown'&&!job.providerId)return writeLifecycle(studio,record,{state:'unknown',error:job.error||'submission_unknown',disclosure:{...record.disclosure,submissionState:'uncertain'}});if(job.state==='failed')return writeLifecycle(studio,record,{state:'failed',error:job.error||'provider_failed',providerStatus:job.providerStatus||null,spending:{...record.spending,spentUsd:job.charge?.actualUsd??null}});if(job.state!=='ready')return writeLifecycle(studio,record,{state:job.state,error:job.error||null,providerStatus:job.providerStatus||null});const profile=await ensureMediaProfile(studio,job.output),providerEvidence=evidenceFor(record,job),audio=audioHandling(profile),freshStatus=readGenerativeInsert(studio,projectId,id);let landing={attached:false,reason:'insert-slot-awaits-artist',targetCurrent:freshStatus.current};if(record.landing.kind==='take-stack'){try{landing=await attachAlternateCandidate(studio,record,job,providerEvidence,audio);}catch(e){landing={attached:false,reason:e.message};}}const readyState=landing.attached?'ready-candidate':record.landing.kind!=='take-stack'&&freshStatus.current?'ready-insert':'ready-historical';return writeLifecycle(studio,record,{state:readyState,error:job.error||null,outputAssetId:job.output,media:job.media,providerEvidence,audioHandling:audio,landingResult:landing,spending:{...record.spending,spentUsd:job.charge?.actualUsd??null},disclosure:{...record.disclosure,submissionState:'completed'}});}
